spring:
  jpa:
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        generate_statistics: false
        format_sql: true
        default_batch_fetch_size: 1000
        show_sql: true
      org:
        hibernate:
          envers:
            audit_table_suffix: Revisions
            revision_field_name: revisionId
            store_data_at_delete: truev
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/h2/test
    username: sa
    password:
